// AUTOGENERATED by scripts/gen-types.ts -- do not edit by hand.
// Regenerate after a migration with: npm run db:types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      audit_logs: {
        Row: {
          id: number;
          actor_id: string | null;
          actor_email: string | null;
          action: string;
          entity_type: string;
          entity_id: string | null;
          metadata: Json;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: number;
          actor_id?: string | null;
          actor_email?: string | null;
          action: string;
          entity_type: string;
          entity_id?: string | null;
          metadata?: Json;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          actor_id?: string | null;
          actor_email?: string | null;
          action?: string;
          entity_type?: string;
          entity_id?: string | null;
          metadata?: Json;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      blocked_dates: {
        Row: {
          id: string;
          salon_id: string;
          date: string;
          is_closed: boolean;
          opens_at: string | null;
          closes_at: string | null;
          reason: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          salon_id: string;
          date: string;
          is_closed?: boolean;
          opens_at?: string | null;
          closes_at?: string | null;
          reason?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          salon_id?: string;
          date?: string;
          is_closed?: boolean;
          opens_at?: string | null;
          closes_at?: string | null;
          reason?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      booking_items: {
        Row: {
          id: string;
          booking_id: string;
          addon_id: string | null;
          kind: string;
          name: string;
          quantity: number;
          unit_price_pence: number;
          duration_minutes: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          booking_id: string;
          addon_id?: string | null;
          kind: string;
          name: string;
          quantity?: number;
          unit_price_pence: number;
          duration_minutes?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          booking_id?: string;
          addon_id?: string | null;
          kind?: string;
          name?: string;
          quantity?: number;
          unit_price_pence?: number;
          duration_minutes?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      bookings: {
        Row: {
          id: string;
          reference: string;
          salon_id: string;
          staff_id: string;
          profile_id: string;
          service_id: string;
          status: Database["public"]["Enums"]["booking_status"];
          starts_at: string;
          ends_at: string;
          blocked_until: string;
          service_price_pence: number;
          addons_price_pence: number;
          discount_pence: number;
          total_price_pence: number;
          deposit_pence: number;
          deposit_paid_pence: number;
          balance_paid_pence: number;
          pricing_mode: Database["public"]["Enums"]["pricing_mode"];
          customer_notes: string | null;
          accessibility_requirements: string | null;
          internal_notes: string | null;
          booked_by_staff_id: string | null;
          is_walk_in: boolean;
          source: string;
          cancelled_at: string | null;
          cancellation_reason: string | null;
          cancelled_by: string | null;
          rescheduled_from: string | null;
          completed_at: string | null;
          reminder_sent_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          reference: string;
          salon_id: string;
          staff_id: string;
          profile_id: string;
          service_id: string;
          status?: Database["public"]["Enums"]["booking_status"];
          starts_at: string;
          ends_at: string;
          blocked_until: string;
          service_price_pence: number;
          addons_price_pence?: number;
          discount_pence?: number;
          total_price_pence: number;
          deposit_pence?: number;
          deposit_paid_pence?: number;
          balance_paid_pence?: number;
          pricing_mode?: Database["public"]["Enums"]["pricing_mode"];
          customer_notes?: string | null;
          accessibility_requirements?: string | null;
          internal_notes?: string | null;
          booked_by_staff_id?: string | null;
          is_walk_in?: boolean;
          source?: string;
          cancelled_at?: string | null;
          cancellation_reason?: string | null;
          cancelled_by?: string | null;
          rescheduled_from?: string | null;
          completed_at?: string | null;
          reminder_sent_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          reference?: string;
          salon_id?: string;
          staff_id?: string;
          profile_id?: string;
          service_id?: string;
          status?: Database["public"]["Enums"]["booking_status"];
          starts_at?: string;
          ends_at?: string;
          blocked_until?: string;
          service_price_pence?: number;
          addons_price_pence?: number;
          discount_pence?: number;
          total_price_pence?: number;
          deposit_pence?: number;
          deposit_paid_pence?: number;
          balance_paid_pence?: number;
          pricing_mode?: Database["public"]["Enums"]["pricing_mode"];
          customer_notes?: string | null;
          accessibility_requirements?: string | null;
          internal_notes?: string | null;
          booked_by_staff_id?: string | null;
          is_walk_in?: boolean;
          source?: string;
          cancelled_at?: string | null;
          cancellation_reason?: string | null;
          cancelled_by?: string | null;
          rescheduled_from?: string | null;
          completed_at?: string | null;
          reminder_sent_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      client_notes: {
        Row: {
          id: string;
          profile_id: string;
          booking_id: string | null;
          author_id: string | null;
          body: string;
          kind: string;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          booking_id?: string | null;
          author_id?: string | null;
          body: string;
          kind?: string;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          booking_id?: string | null;
          author_id?: string | null;
          body?: string;
          kind?: string;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      client_photos: {
        Row: {
          id: string;
          profile_id: string;
          booking_id: string | null;
          storage_path: string;
          kind: string;
          caption: string | null;
          service_id: string | null;
          consent_record_id: string | null;
          is_published: boolean;
          uploaded_by: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          booking_id?: string | null;
          storage_path: string;
          kind: string;
          caption?: string | null;
          service_id?: string | null;
          consent_record_id?: string | null;
          is_published?: boolean;
          uploaded_by?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          booking_id?: string | null;
          storage_path?: string;
          kind?: string;
          caption?: string | null;
          service_id?: string | null;
          consent_record_id?: string | null;
          is_published?: boolean;
          uploaded_by?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      client_tag_links: {
        Row: {
          profile_id: string;
          tag_id: string;
          applied_by: string | null;
          created_at: string;
        };
        Insert: {
          profile_id: string;
          tag_id: string;
          applied_by?: string | null;
          created_at?: string;
        };
        Update: {
          profile_id?: string;
          tag_id?: string;
          applied_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      client_tags: {
        Row: {
          id: string;
          salon_id: string;
          name: string;
          colour: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          salon_id: string;
          name: string;
          colour?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          salon_id?: string;
          name?: string;
          colour?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      consent_records: {
        Row: {
          id: string;
          profile_id: string;
          kind: Database["public"]["Enums"]["consent_kind"];
          granted: boolean;
          document_version: string | null;
          source: string;
          ip_address: string | null;
          user_agent: string | null;
          recorded_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          kind: Database["public"]["Enums"]["consent_kind"];
          granted: boolean;
          document_version?: string | null;
          source?: string;
          ip_address?: string | null;
          user_agent?: string | null;
          recorded_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          kind?: Database["public"]["Enums"]["consent_kind"];
          granted?: boolean;
          document_version?: string | null;
          source?: string;
          ip_address?: string | null;
          user_agent?: string | null;
          recorded_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      discount_codes: {
        Row: {
          id: string;
          salon_id: string;
          code: string;
          description: string | null;
          percent_off: number | null;
          amount_off_pence: number | null;
          minimum_spend_pence: number;
          service_id: string | null;
          max_redemptions: number | null;
          redemption_count: number;
          starts_at: string | null;
          ends_at: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          salon_id: string;
          code: string;
          description?: string | null;
          percent_off?: number | null;
          amount_off_pence?: number | null;
          minimum_spend_pence?: number;
          service_id?: string | null;
          max_redemptions?: number | null;
          redemption_count?: number;
          starts_at?: string | null;
          ends_at?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          salon_id?: string;
          code?: string;
          description?: string | null;
          percent_off?: number | null;
          amount_off_pence?: number | null;
          minimum_spend_pence?: number;
          service_id?: string | null;
          max_redemptions?: number | null;
          redemption_count?: number;
          starts_at?: string | null;
          ends_at?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      discount_redemptions: {
        Row: {
          id: string;
          discount_code_id: string;
          booking_id: string;
          amount_pence: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          discount_code_id: string;
          booking_id: string;
          amount_pence: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          discount_code_id?: string;
          booking_id?: string;
          amount_pence?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      gift_card_redemptions: {
        Row: {
          id: string;
          gift_card_id: string;
          booking_id: string | null;
          amount_pence: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          gift_card_id: string;
          booking_id?: string | null;
          amount_pence: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          gift_card_id?: string;
          booking_id?: string | null;
          amount_pence?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      gift_cards: {
        Row: {
          id: string;
          salon_id: string;
          code: string;
          initial_balance_pence: number;
          balance_pence: number;
          purchaser_profile_id: string | null;
          recipient_email: string | null;
          expires_at: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          salon_id: string;
          code: string;
          initial_balance_pence: number;
          balance_pence: number;
          purchaser_profile_id?: string | null;
          recipient_email?: string | null;
          expires_at?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          salon_id?: string;
          code?: string;
          initial_balance_pence?: number;
          balance_pence?: number;
          purchaser_profile_id?: string | null;
          recipient_email?: string | null;
          expires_at?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      import_runs: {
        Row: {
          id: string;
          salon_id: string;
          kind: string;
          status: Database["public"]["Enums"]["import_status"];
          source_filename: string | null;
          field_mapping: Json;
          report: Json;
          total_rows: number;
          valid_rows: number;
          imported_rows: number;
          duplicate_rows: number;
          error_rows: number;
          created_record_ids: string[];
          applied_at: string | null;
          rolled_back_at: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          salon_id: string;
          kind: string;
          status?: Database["public"]["Enums"]["import_status"];
          source_filename?: string | null;
          field_mapping?: Json;
          report?: Json;
          total_rows?: number;
          valid_rows?: number;
          imported_rows?: number;
          duplicate_rows?: number;
          error_rows?: number;
          created_record_ids?: string[];
          applied_at?: string | null;
          rolled_back_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          salon_id?: string;
          kind?: string;
          status?: Database["public"]["Enums"]["import_status"];
          source_filename?: string | null;
          field_mapping?: Json;
          report?: Json;
          total_rows?: number;
          valid_rows?: number;
          imported_rows?: number;
          duplicate_rows?: number;
          error_rows?: number;
          created_record_ids?: string[];
          applied_at?: string | null;
          rolled_back_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      memberships: {
        Row: {
          id: string;
          salon_id: string;
          profile_id: string | null;
          email: string;
          programme_id: string;
          programme_name: string;
          category: string | null;
          tier: string;
          payment: string;
          status: string;
          total_pence: number;
          amount_now_pence: number;
          months: number | null;
          included_visits: number;
          completed_visits: number;
          next_visit_at: string | null;
          booking_reference: string | null;
          stripe_checkout_session_id: string | null;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          stripe_payment_intent_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          salon_id: string;
          profile_id?: string | null;
          email: string;
          programme_id: string;
          programme_name: string;
          category?: string | null;
          tier: string;
          payment: string;
          status?: string;
          total_pence: number;
          amount_now_pence?: number;
          months?: number | null;
          included_visits?: number;
          completed_visits?: number;
          next_visit_at?: string | null;
          booking_reference?: string | null;
          stripe_checkout_session_id?: string | null;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          stripe_payment_intent_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          salon_id?: string;
          profile_id?: string | null;
          email?: string;
          programme_id?: string;
          programme_name?: string;
          category?: string | null;
          tier?: string;
          payment?: string;
          status?: string;
          total_pence?: number;
          amount_now_pence?: number;
          months?: number | null;
          included_visits?: number;
          completed_visits?: number;
          next_visit_at?: string | null;
          booking_reference?: string | null;
          stripe_checkout_session_id?: string | null;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          stripe_payment_intent_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      message_deliveries: {
        Row: {
          id: string;
          salon_id: string;
          profile_id: string | null;
          booking_id: string | null;
          template_id: string | null;
          kind: Database["public"]["Enums"]["message_kind"];
          channel: Database["public"]["Enums"]["message_channel"];
          status: Database["public"]["Enums"]["message_delivery_status"];
          idempotency_key: string;
          recipient: string;
          subject: string | null;
          body: string;
          provider: string | null;
          provider_message_id: string | null;
          error_message: string | null;
          scheduled_for: string | null;
          sent_at: string | null;
          attempts: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          salon_id: string;
          profile_id?: string | null;
          booking_id?: string | null;
          template_id?: string | null;
          kind: Database["public"]["Enums"]["message_kind"];
          channel: Database["public"]["Enums"]["message_channel"];
          status?: Database["public"]["Enums"]["message_delivery_status"];
          idempotency_key: string;
          recipient: string;
          subject?: string | null;
          body: string;
          provider?: string | null;
          provider_message_id?: string | null;
          error_message?: string | null;
          scheduled_for?: string | null;
          sent_at?: string | null;
          attempts?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          salon_id?: string;
          profile_id?: string | null;
          booking_id?: string | null;
          template_id?: string | null;
          kind?: Database["public"]["Enums"]["message_kind"];
          channel?: Database["public"]["Enums"]["message_channel"];
          status?: Database["public"]["Enums"]["message_delivery_status"];
          idempotency_key?: string;
          recipient?: string;
          subject?: string | null;
          body?: string;
          provider?: string | null;
          provider_message_id?: string | null;
          error_message?: string | null;
          scheduled_for?: string | null;
          sent_at?: string | null;
          attempts?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      message_templates: {
        Row: {
          id: string;
          salon_id: string;
          kind: Database["public"]["Enums"]["message_kind"];
          channel: Database["public"]["Enums"]["message_channel"];
          subject: string | null;
          body: string;
          is_active: boolean;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          salon_id: string;
          kind: Database["public"]["Enums"]["message_kind"];
          channel: Database["public"]["Enums"]["message_channel"];
          subject?: string | null;
          body: string;
          is_active?: boolean;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          salon_id?: string;
          kind?: Database["public"]["Enums"]["message_kind"];
          channel?: Database["public"]["Enums"]["message_channel"];
          subject?: string | null;
          body?: string;
          is_active?: boolean;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      opening_hours: {
        Row: {
          id: string;
          salon_id: string;
          day_of_week: number;
          opens_at: string;
          closes_at: string;
          is_closed: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          salon_id: string;
          day_of_week: number;
          opens_at: string;
          closes_at: string;
          is_closed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          salon_id?: string;
          day_of_week?: number;
          opens_at?: string;
          closes_at?: string;
          is_closed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      payments: {
        Row: {
          id: string;
          booking_id: string | null;
          profile_id: string | null;
          salon_id: string;
          email: string | null;
          kind: Database["public"]["Enums"]["payment_kind"];
          status: Database["public"]["Enums"]["payment_status"];
          amount_pence: number;
          refunded_pence: number;
          currency: string;
          stripe_payment_intent_id: string | null;
          stripe_charge_id: string | null;
          stripe_customer_id: string | null;
          payment_method_brand: string | null;
          payment_method_last4: string | null;
          receipt_url: string | null;
          recorded_by_staff_id: string | null;
          notes: string | null;
          failure_code: string | null;
          failure_message: string | null;
          paid_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          booking_id?: string | null;
          profile_id?: string | null;
          salon_id: string;
          email?: string | null;
          kind: Database["public"]["Enums"]["payment_kind"];
          status?: Database["public"]["Enums"]["payment_status"];
          amount_pence: number;
          refunded_pence?: number;
          currency?: string;
          stripe_payment_intent_id?: string | null;
          stripe_charge_id?: string | null;
          stripe_customer_id?: string | null;
          payment_method_brand?: string | null;
          payment_method_last4?: string | null;
          receipt_url?: string | null;
          recorded_by_staff_id?: string | null;
          notes?: string | null;
          failure_code?: string | null;
          failure_message?: string | null;
          paid_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          booking_id?: string | null;
          profile_id?: string | null;
          salon_id?: string;
          email?: string | null;
          kind?: Database["public"]["Enums"]["payment_kind"];
          status?: Database["public"]["Enums"]["payment_status"];
          amount_pence?: number;
          refunded_pence?: number;
          currency?: string;
          stripe_payment_intent_id?: string | null;
          stripe_charge_id?: string | null;
          stripe_customer_id?: string | null;
          payment_method_brand?: string | null;
          payment_method_last4?: string | null;
          receipt_url?: string | null;
          recorded_by_staff_id?: string | null;
          notes?: string | null;
          failure_code?: string | null;
          failure_message?: string | null;
          paid_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          email: string;
          first_name: string;
          last_name: string;
          phone: string | null;
          birthday: string | null;
          hair_goals: string | null;
          accessibility_requirements: string | null;
          allergies: string | null;
          favourite_staff_id: string | null;
          marketing_email: boolean;
          marketing_sms: boolean;
          reminder_email: boolean;
          reminder_sms: boolean;
          no_show_count: number;
          cancellation_count: number;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          first_name?: string;
          last_name?: string;
          phone?: string | null;
          birthday?: string | null;
          hair_goals?: string | null;
          accessibility_requirements?: string | null;
          allergies?: string | null;
          favourite_staff_id?: string | null;
          marketing_email?: boolean;
          marketing_sms?: boolean;
          reminder_email?: boolean;
          reminder_sms?: boolean;
          no_show_count?: number;
          cancellation_count?: number;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          first_name?: string;
          last_name?: string;
          phone?: string | null;
          birthday?: string | null;
          hair_goals?: string | null;
          accessibility_requirements?: string | null;
          allergies?: string | null;
          favourite_staff_id?: string | null;
          marketing_email?: boolean;
          marketing_sms?: boolean;
          reminder_email?: boolean;
          reminder_sms?: boolean;
          no_show_count?: number;
          cancellation_count?: number;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      refunds: {
        Row: {
          id: string;
          payment_id: string;
          booking_id: string | null;
          amount_pence: number;
          reason: string | null;
          stripe_refund_id: string | null;
          status: Database["public"]["Enums"]["payment_status"];
          issued_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          payment_id: string;
          booking_id?: string | null;
          amount_pence: number;
          reason?: string | null;
          stripe_refund_id?: string | null;
          status?: Database["public"]["Enums"]["payment_status"];
          issued_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          payment_id?: string;
          booking_id?: string | null;
          amount_pence?: number;
          reason?: string | null;
          stripe_refund_id?: string | null;
          status?: Database["public"]["Enums"]["payment_status"];
          issued_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      salon_settings: {
        Row: {
          id: string;
          salon_id: string;
          key: string;
          value: Json;
          description: string | null;
          is_sensitive: boolean;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          salon_id: string;
          key: string;
          value?: Json;
          description?: string | null;
          is_sensitive?: boolean;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          salon_id?: string;
          key?: string;
          value?: Json;
          description?: string | null;
          is_sensitive?: boolean;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      salons: {
        Row: {
          id: string;
          name: string;
          slug: string;
          address_line1: string;
          address_line2: string | null;
          city: string;
          postcode: string;
          country_code: string;
          latitude: number | null;
          longitude: number | null;
          phone: string | null;
          email: string | null;
          timezone: string;
          currency: string;
          booking_window_days: number;
          min_notice_minutes: number;
          cancellation_window_hours: number;
          reschedule_window_hours: number;
          slot_interval_minutes: number;
          hold_duration_minutes: number;
          deposit_required: boolean;
          allow_full_payment: boolean;
          tagline: string | null;
          about: string | null;
          instagram_url: string | null;
          facebook_url: string | null;
          google_maps_url: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          address_line1: string;
          address_line2?: string | null;
          city: string;
          postcode: string;
          country_code?: string;
          latitude?: number | null;
          longitude?: number | null;
          phone?: string | null;
          email?: string | null;
          timezone?: string;
          currency?: string;
          booking_window_days?: number;
          min_notice_minutes?: number;
          cancellation_window_hours?: number;
          reschedule_window_hours?: number;
          slot_interval_minutes?: number;
          hold_duration_minutes?: number;
          deposit_required?: boolean;
          allow_full_payment?: boolean;
          tagline?: string | null;
          about?: string | null;
          instagram_url?: string | null;
          facebook_url?: string | null;
          google_maps_url?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          address_line1?: string;
          address_line2?: string | null;
          city?: string;
          postcode?: string;
          country_code?: string;
          latitude?: number | null;
          longitude?: number | null;
          phone?: string | null;
          email?: string | null;
          timezone?: string;
          currency?: string;
          booking_window_days?: number;
          min_notice_minutes?: number;
          cancellation_window_hours?: number;
          reschedule_window_hours?: number;
          slot_interval_minutes?: number;
          hold_duration_minutes?: number;
          deposit_required?: boolean;
          allow_full_payment?: boolean;
          tagline?: string | null;
          about?: string | null;
          instagram_url?: string | null;
          facebook_url?: string | null;
          google_maps_url?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      service_addon_links: {
        Row: {
          service_id: string;
          addon_id: string;
          created_at: string;
        };
        Insert: {
          service_id: string;
          addon_id: string;
          created_at?: string;
        };
        Update: {
          service_id?: string;
          addon_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      service_addons: {
        Row: {
          id: string;
          salon_id: string;
          name: string;
          slug: string;
          description: string | null;
          duration_minutes: number;
          price_pence: number;
          display_order: number;
          is_active: boolean;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          salon_id: string;
          name: string;
          slug: string;
          description?: string | null;
          duration_minutes?: number;
          price_pence?: number;
          display_order?: number;
          is_active?: boolean;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          salon_id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          duration_minutes?: number;
          price_pence?: number;
          display_order?: number;
          is_active?: boolean;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      service_categories: {
        Row: {
          id: string;
          salon_id: string;
          name: string;
          slug: string;
          description: string | null;
          display_order: number;
          is_active: boolean;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          salon_id: string;
          name: string;
          slug: string;
          description?: string | null;
          display_order?: number;
          is_active?: boolean;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          salon_id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          display_order?: number;
          is_active?: boolean;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      services: {
        Row: {
          id: string;
          salon_id: string;
          category_id: string | null;
          name: string;
          slug: string;
          description: string;
          short_description: string | null;
          preparation_instructions: string | null;
          aftercare_instructions: string | null;
          duration_minutes: number;
          buffer_minutes: number;
          base_price_pence: number;
          pricing_mode: Database["public"]["Enums"]["pricing_mode"];
          deposit_pence: number;
          cancellation_window_hours: number | null;
          requires_consultation: boolean;
          rebooking_interval_days: number | null;
          image_url: string | null;
          image_alt: string | null;
          display_order: number;
          is_featured: boolean;
          is_active: boolean;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          salon_id: string;
          category_id?: string | null;
          name: string;
          slug: string;
          description?: string;
          short_description?: string | null;
          preparation_instructions?: string | null;
          aftercare_instructions?: string | null;
          duration_minutes: number;
          buffer_minutes?: number;
          base_price_pence: number;
          pricing_mode?: Database["public"]["Enums"]["pricing_mode"];
          deposit_pence?: number;
          cancellation_window_hours?: number | null;
          requires_consultation?: boolean;
          rebooking_interval_days?: number | null;
          image_url?: string | null;
          image_alt?: string | null;
          display_order?: number;
          is_featured?: boolean;
          is_active?: boolean;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          salon_id?: string;
          category_id?: string | null;
          name?: string;
          slug?: string;
          description?: string;
          short_description?: string | null;
          preparation_instructions?: string | null;
          aftercare_instructions?: string | null;
          duration_minutes?: number;
          buffer_minutes?: number;
          base_price_pence?: number;
          pricing_mode?: Database["public"]["Enums"]["pricing_mode"];
          deposit_pence?: number;
          cancellation_window_hours?: number | null;
          requires_consultation?: boolean;
          rebooking_interval_days?: number | null;
          image_url?: string | null;
          image_alt?: string | null;
          display_order?: number;
          is_featured?: boolean;
          is_active?: boolean;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      slot_holds: {
        Row: {
          id: string;
          salon_id: string;
          staff_id: string;
          service_id: string;
          profile_id: string | null;
          hold_token: string;
          starts_at: string;
          ends_at: string;
          blocked_until: string;
          expires_at: string;
          consumed_at: string | null;
          booking_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          salon_id: string;
          staff_id: string;
          service_id: string;
          profile_id?: string | null;
          hold_token?: string;
          starts_at: string;
          ends_at: string;
          blocked_until: string;
          expires_at: string;
          consumed_at?: string | null;
          booking_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          salon_id?: string;
          staff_id?: string;
          service_id?: string;
          profile_id?: string | null;
          hold_token?: string;
          starts_at?: string;
          ends_at?: string;
          blocked_until?: string;
          expires_at?: string;
          consumed_at?: string | null;
          booking_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      staff: {
        Row: {
          id: string;
          salon_id: string;
          profile_id: string | null;
          display_name: string;
          slug: string;
          title: string | null;
          bio: string | null;
          specialties: string[];
          image_url: string | null;
          image_alt: string | null;
          is_bookable: boolean;
          is_active: boolean;
          display_order: number;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          salon_id: string;
          profile_id?: string | null;
          display_name: string;
          slug: string;
          title?: string | null;
          bio?: string | null;
          specialties?: string[];
          image_url?: string | null;
          image_alt?: string | null;
          is_bookable?: boolean;
          is_active?: boolean;
          display_order?: number;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          salon_id?: string;
          profile_id?: string | null;
          display_name?: string;
          slug?: string;
          title?: string | null;
          bio?: string | null;
          specialties?: string[];
          image_url?: string | null;
          image_alt?: string | null;
          is_bookable?: boolean;
          is_active?: boolean;
          display_order?: number;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      staff_breaks: {
        Row: {
          id: string;
          staff_id: string;
          day_of_week: number;
          starts_at: string;
          ends_at: string;
          label: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          staff_id: string;
          day_of_week: number;
          starts_at: string;
          ends_at: string;
          label?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          staff_id?: string;
          day_of_week?: number;
          starts_at?: string;
          ends_at?: string;
          label?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      staff_schedules: {
        Row: {
          id: string;
          staff_id: string;
          day_of_week: number;
          starts_at: string;
          ends_at: string;
          effective_from: string | null;
          effective_to: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          staff_id: string;
          day_of_week: number;
          starts_at: string;
          ends_at: string;
          effective_from?: string | null;
          effective_to?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          staff_id?: string;
          day_of_week?: number;
          starts_at?: string;
          ends_at?: string;
          effective_from?: string | null;
          effective_to?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      staff_services: {
        Row: {
          staff_id: string;
          service_id: string;
          duration_override_minutes: number | null;
          price_override_pence: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          staff_id: string;
          service_id: string;
          duration_override_minutes?: number | null;
          price_override_pence?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          staff_id?: string;
          service_id?: string;
          duration_override_minutes?: number | null;
          price_override_pence?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      staff_time_off: {
        Row: {
          id: string;
          staff_id: string;
          starts_at: string;
          ends_at: string;
          reason: string | null;
          is_approved: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          staff_id: string;
          starts_at: string;
          ends_at: string;
          reason?: string | null;
          is_approved?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          staff_id?: string;
          starts_at?: string;
          ends_at?: string;
          reason?: string | null;
          is_approved?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      user_roles: {
        Row: {
          id: string;
          user_id: string;
          role: Database["public"]["Enums"]["user_role"];
          granted_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          role: Database["public"]["Enums"]["user_role"];
          granted_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          role?: Database["public"]["Enums"]["user_role"];
          granted_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      waitlist_entries: {
        Row: {
          id: string;
          salon_id: string;
          profile_id: string;
          service_id: string;
          staff_id: string | null;
          earliest_date: string;
          latest_date: string;
          times_of_day: Database["public"]["Enums"]["time_of_day"][];
          status: Database["public"]["Enums"]["waitlist_status"];
          offered_at: string | null;
          offer_expires_at: string | null;
          offered_slot_starts_at: string | null;
          offered_staff_id: string | null;
          offer_token: string | null;
          converted_booking_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          salon_id: string;
          profile_id: string;
          service_id: string;
          staff_id?: string | null;
          earliest_date: string;
          latest_date: string;
          times_of_day?: Database["public"]["Enums"]["time_of_day"][];
          status?: Database["public"]["Enums"]["waitlist_status"];
          offered_at?: string | null;
          offer_expires_at?: string | null;
          offered_slot_starts_at?: string | null;
          offered_staff_id?: string | null;
          offer_token?: string | null;
          converted_booking_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          salon_id?: string;
          profile_id?: string;
          service_id?: string;
          staff_id?: string | null;
          earliest_date?: string;
          latest_date?: string;
          times_of_day?: Database["public"]["Enums"]["time_of_day"][];
          status?: Database["public"]["Enums"]["waitlist_status"];
          offered_at?: string | null;
          offer_expires_at?: string | null;
          offered_slot_starts_at?: string | null;
          offered_staff_id?: string | null;
          offer_token?: string | null;
          converted_booking_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      /** available_slots(p_service_id uuid, p_from date, p_to date, p_staff_id uuid DEFAULT NULL::uuid, p_extra_minutes integer DEFAULT 0) -> TABLE(staff_id uuid, staff_name text, slot_start timestamp with time zone, slot_end timestamp with time zone, blocked_until timestamp with time zone) */
      available_slots: {
        Args: Record<string, unknown>;
        Returns: unknown;
      };
      /** book_slot(p_hold_token uuid, p_profile_id uuid, p_addon_ids uuid[] DEFAULT '{}'::uuid[], p_customer_notes text DEFAULT NULL::text, p_accessibility_requirements text DEFAULT NULL::text, p_source text DEFAULT 'web'::text, p_discount_code text DEFAULT NULL::text) -> bookings */
      book_slot: {
        Args: Record<string, unknown>;
        Returns: unknown;
      };
      /** confirm_booking_paid(p_booking_id uuid, p_amount_pence integer, p_kind payment_kind DEFAULT 'deposit'::payment_kind) -> bookings */
      confirm_booking_paid: {
        Args: Record<string, unknown>;
        Returns: unknown;
      };
      /** effective_service_terms(p_staff_id uuid, p_service_id uuid) -> TABLE(duration_minutes integer, buffer_minutes integer, price_pence integer, deposit_pence integer, pricing_mode pricing_mode) */
      effective_service_terms: {
        Args: Record<string, unknown>;
        Returns: unknown;
      };
      /** hold_slot(p_staff_id uuid, p_service_id uuid, p_starts_at timestamp with time zone, p_profile_id uuid DEFAULT NULL::uuid, p_addon_ids uuid[] DEFAULT '{}'::uuid[]) -> slot_holds */
      hold_slot: {
        Args: Record<string, unknown>;
        Returns: unknown;
      };
      /** is_slot_available(p_staff_id uuid, p_service_id uuid, p_starts_at timestamp with time zone, p_blocked_until timestamp with time zone, p_ignore_booking_id uuid DEFAULT NULL::uuid, p_ignore_hold_id uuid DEFAULT NULL::uuid) -> boolean */
      is_slot_available: {
        Args: Record<string, unknown>;
        Returns: unknown;
      };
      /** next_available_slot(p_service_id uuid, p_staff_id uuid DEFAULT NULL::uuid) -> TABLE(staff_id uuid, staff_name text, slot_start timestamp with time zone, slot_end timestamp with time zone, blocked_until timestamp with time zone) */
      next_available_slot: {
        Args: Record<string, unknown>;
        Returns: unknown;
      };
      /** release_expired_holds(p_staff_id uuid DEFAULT NULL::uuid) -> integer */
      release_expired_holds: {
        Args: Record<string, unknown>;
        Returns: unknown;
      };
      /** reschedule_booking(p_booking_id uuid, p_staff_id uuid, p_starts_at timestamp with time zone) -> bookings */
      reschedule_booking: {
        Args: Record<string, unknown>;
        Returns: unknown;
      };
    };
    Enums: {
      booking_status: "pending_payment" | "confirmed" | "completed" | "cancelled_by_customer" | "cancelled_by_salon" | "no_show";
      consent_kind: "marketing_email" | "marketing_sms" | "photo_publication" | "terms" | "privacy";
      import_status: "draft" | "previewed" | "applied" | "rolled_back" | "failed";
      message_channel: "email" | "sms";
      message_delivery_status: "queued" | "sent" | "delivered" | "failed" | "skipped";
      message_kind: "booking_confirmation" | "deposit_receipt" | "appointment_reminder" | "reschedule_confirmation" | "cancellation_confirmation" | "waitlist_availability" | "payment_failure" | "refund_confirmation" | "post_appointment_thanks" | "review_request" | "rebooking_reminder" | "marketing_campaign";
      payment_kind: "deposit" | "balance" | "full" | "in_salon";
      payment_status: "requires_payment" | "processing" | "succeeded" | "failed" | "refunded" | "partially_refunded" | "disputed";
      pricing_mode: "fixed" | "from";
      time_of_day: "morning" | "afternoon" | "evening";
      user_role: "customer" | "stylist" | "receptionist" | "manager" | "admin";
      waitlist_status: "active" | "offered" | "converted" | "expired" | "cancelled";
    };
    CompositeTypes: Record<string, never>;
  };
};

type PublicSchema = Database["public"];
export type Tables<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T]["Row"];
export type TablesInsert<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T]["Update"];
export type Enums<T extends keyof PublicSchema["Enums"]> =
  PublicSchema["Enums"][T];
